services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${BACKEND_PORT}:8000"
    networks:
      - app-network
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - REACT_APP_BACKEND_IP=${BACKEND_IP}
      - REACT_APP_BACKEND_PORT=${BACKEND_PORT}

networks:
  app-network:
    driver: bridge