services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${BACKEND_PORT}:8000"
    networks:
      - app-network
    environment:
      - BACKEND_IP=${BACKEND_IP}
      - FRONTEND_PORT=${FRONTEND_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
      - REACT_APP_BACKEND_IP=${BACKEND_IP}
      - REACT_APP_BACKEND_PORT=${BACKEND_PORT}
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - REACT_APP_BACKEND_IP=${BACKEND_IP}
      - REACT_APP_BACKEND_PORT=${BACKEND_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge